name: Build and Push Docker Image (Spring Boot)

on:
  push:
    branches: [ main ]  # main 브랜치에 푸시 시 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .  # Dockerfile이 있는 루트 경로
          file: Dockerfile  # Dockerfile 경로 지정
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest
